### ISSUE TITLE
【Can't Play】やってみよう

### ISSUE THREAD

**Issue by AkihiroTokai** [lit-kansai-members/music#110]
2017 Spring Campのやってみようが再生できない状態なので代替Contents調査します。

**Comment by mizucoffee** [comment]
https://www.youtube.com/watch?v=XWC9c3vFx8c

**Comment by AkihiroTokai** [comment]
@mizucoffee ↑のものが再生できない状態になっていることを確認したのでReopenします。

**Comment by mizucoffee** [comment]
https://www.youtube.com/watch?v=eIja9BI_h9U

**Comment by mizucoffee** [comment]
重複してるのでduplicateを付けてCloseして #132 と統合してください。
