### ISSUE TITLE
ビルドが通らない

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/music#113]
Travis CI落ちる

**Comment by AkihiroTokai** [comment]
それ少し前から通ってなかったですよ（）

**Comment by mizucoffee** [comment]
知ってますが特に更新する理由が無かったので放置してました（）
対応しないとPRをマージ出来ないので...

**Comment by AkihiroTokai** [comment]
>知ってますが特に更新する理由が無かったので放置してました（）  
  
そんな予感はしてました（）~そのあたり面倒な気がしたので誰かやってくれないかなと~

**Comment by mizucoffee** [comment]
レビュー&マージお願いします><
