### ISSUE TITLE
カラオケ番号追加

### ISSUE THREAD

**Issue by ghost** [lit-kansai-members/music#116]
カラオケ予約番号をカラオケ可能な楽曲は追加するのはどうでしょうか(Joysound、DAMあたりを追加とか)

**Comment by AkihiroTokai** [comment]
本人映像・生演奏・ガイドボーカル・ボーカルアシストなどではないオリジナルのものを優先して掲載する。オリジナルのみで併記までは不要？

**Comment by mizucoffee** [comment]
それでいいと思います 👍

**Comment by AkihiroTokai** [comment]
@ygkn @mizucoffee  descriptionの2行目でいいですか？

**Comment by 7io63** [comment]
明瞭にカラオケ番号ってわかるように表記してあれば👌
（eg. 🎤 [JOYSOUND]999999 [DAM]000000 とか）

**Comment by AkihiroTokai** [comment]
量が多いので少しずつやります！

**Comment by AkihiroTokai** [comment]
@7io63 @mizucoffee  @ygkn @OldBigBuddha それぞれの曲ごとにDAMとJOYSOUND集めてもらえると助かります:pray:

**Comment by AkihiroTokai** [comment]
DAMはこっちにします。https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=3844-71

**Comment by AkihiroTokai** [comment]
JOYSOUNDはこのURLで https://www.joysound.com/web/search/song/735036

**Comment by AkihiroTokai** [comment]
## 2019 (
### Xmas
- [ ] lovin'
- [ ] ハピネス
### GLOBAL IT
- [ ] ハピネス
### Summer
- [ ] ハピネス
### EnglishIT
- [ ] ハピネス
### 伊豆
- [ ] ハピネス
### Spring
- [ ] ハピネス

**Comment by AkihiroTokai** [comment]
#206時点での進捗は37曲/のべ90曲のはずです。

**Comment by AkihiroTokai** [comment]
今年中に100曲到達しそうですね！

**Comment by AkihiroTokai** [comment]
2014と2013
2012と番外編
こちらの件に関してはあと2回で完了する予定です！
