### ISSUE TITLE
【Can't Play】変わらないもの

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/music#120]

**Comment by mizucoffee** [comment]
https://www.youtube.com/watch?v=IQnM-chc86U

**Comment by AkihiroTokai** [comment]
ガーネットはあるんですけどね...

**Comment by AkihiroTokai** [comment]
https://www.youtube.com/watch?v=-KRvjsXi9Ds

**Comment by AkihiroTokai** [comment]
😢 😢 😢 😢 😢 
>他のウェブサイトでの再生は、動画の所有者によって無効にされています。

**Comment by AkihiroTokai** [comment]
https://www.youtube.com/watch?v=q7lErGnZlPw

**Comment by AkihiroTokai** [comment]
@mizucoffee @lit-kansai-members/admins もう少し探してみますが、なさそうであれば注釈つけてそのまま掲載しておきましょうか。

**Comment by AkihiroTokai** [comment]
https://www.youtube.com/watch?v=pZs8qn6ZMrM
https://www.youtube.com/watch?v=SqANEGZ6Ty0

**Comment by AkihiroTokai** [comment]
後者を採用してPRします。
