### ISSUE TITLE
【テーマ】2013夏

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/music#129]
「きっと忘れられない夏になる」

提供者：KNTK

**Comment by AkihiroTokai** [comment]
これも独断（複数の情報源なし）で反映していいですか？

**Comment by mizucoffee** [comment]
メンバーからの情報では限界に近い範囲なので大丈夫です
「違うという指摘があれば修正すればいい」というスタンスで行っても良いのではないかと。
