### ISSUE TITLE
【New Song】拝啓、少年よ

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/music#136]
キャンプ：Spring Camp 2019
会場：大阪大学
曲名：拝啓、少年よ
歌手：Hump Back
リンク：https://youtu.be/d6i4AtCxrDo

**Comment by mizucoffee** [comment]
Close #143

**Comment by AkihiroTokai** [comment]
@mizucoffee この春よ、止まれに変更しておきますね！
https://life-is-tech.com/news/report/2019springcamp-report
