### ISSUE TITLE
【New Song】青と夏

### ISSUE THREAD

**Issue by AkihiroTokai** [lit-kansai-members/music#145]
:warning: This song is UNDECIDED .  You can NOT merging until it is confirmed at Summer CAMP 2019  :warning: 

When:Summer2019
Where:(Spring2019@Kansai UNiversity MeRiSE )
Singer:Mrs. GREEN APPLE
URL:https://www.youtube.com/watch?v=m34DPnRUfMU

**Comment by mizucoffee** [comment]
意図があり閉じたのですが...
