### ISSUE TITLE
Can't build on Travis CI

### ISSUE THREAD

**Issue by AkihiroTokai** [lit-kansai-members/music#149]
I checked the Build log 
It seems like #113

**Comment by mizucoffee** [comment]
https://github.com/lit-kansai-members/music/pull/114#issuecomment-454776120

**Comment by AkihiroTokai** [comment]
Latest version(gulp-sass) is  4.0.2:thinking:

**Comment by mizucoffee** [comment]
https://travis-ci.org/lit-kansai-members/music/builds/532409571#L225

**Comment by mizucoffee** [comment]
手元環境では正常にビルド可能なのですが、 @AkihiroTokai さんの環境では如何ですか？

**Comment by AkihiroTokai** [comment]
I was testing on my local develop environment :computer: (Successful:sparkles:) before send the PR...

**Comment by AkihiroTokai** [comment]
https://github.com/travis-ci/travis-ci/issues/9445
https://travis-ci.community/t/upgrade-yarn-to-a-newer-version/2135

**Comment by AkihiroTokai** [comment]
Fixed:#148
