### ISSUE TITLE
パララックス

### ISSUE THREAD

**Issue by lra21711214** [lit-kansai-members/music#155]
パララックスの写真が荒ぶるから直したほうがいい

**Comment by mizucoffee** [comment]
よろしければ環境（OS/ブラウザ）を教えてくださいー！

**Comment by mizucoffee** [comment]
（まあ多分v2でパララックス自体廃止される可能性も高いんですが...）

**Comment by lra21711214** [comment]
MacOS Mojava V10.14.5
Chrome Version 75.0.3770.100

スクロールした時に背景が動くから固定した方がみやすいと思う

**Comment by mizucoffee** [comment]
手元だと

Mac/Chrome: がくつく
Mac/Safari:がくつく
Mac/Firefox:がくつく
ArchLinux/Chorme: ぬるぬる

これ多分mac特有のスクロールのせいなんすよねー

**Comment by mizucoffee** [comment]
@ygkn v2でもパララックスする？

**Comment by lra21711214** [comment]
これとか参考に作ってみればガタつかないと思うよ！！
https://github.com/lra21711214/parallax

**Comment by ygkn** [comment]
> これ多分mac特有のスクロールのせいなんすよねー

Ubuntu + Chromeでも微妙にがくつく()

> @ygkn v2でもパララックスする？

どうしようかなー
そもそも壁紙使ってるのはOKなんだろうか

> これとか参考に作ってみればガタつかないと思うよ！！
> https://github.com/lra21711214/parallax

その方法は把握してますが意図している動作ではないです。

https://keithclark.co.uk/articles/pure-css-parallax-websites/demo3/

こっちですね。

**Comment by lra21711214** [comment]
https://www.leo-webdesign.com/pc/

これとか、参考にできるかな？？
もしあれだったらソースコード渡します！！

**Comment by ygkn** [comment]
パララックスは継続することになりそうなのでReopen

**Comment by ygkn** [comment]
上記の Pure CSS Parallax、`overflow: hidden`を適用してもスクロールできてしまう……。
ググってみても原因が出てこないのでいろいろ実験してみる。

**Comment by ygkn** [comment]
縦も横もスクロールイベントが発火してないという面白い現象が起こってますねえ

**Comment by ygkn** [comment]
@lra21711214 @mizucoffee ちなみにMacでパララックスの画像(`.parallax > .background`)に`will-change: transform;`を追加するとどうなります？

**Comment by ygkn** [comment]
> 上記の Pure CSS Parallax、`overflow-x: hidden`を適用してもスクロールできてしまう……。
> ググってみても原因が出てこないのでいろいろ実験してみる。

この件、完全に理解した

**Comment by ygkn** [comment]
> https://www.leo-webdesign.com/pc/
> 
> これとか、参考にできるかな？？
> もしあれだったらソースコード渡します！！

この手法がパララックスさせる要素ですが、パララックスさせる要素の親要素がそれぞれ`100vh*100vw`じゃないと使えないので使えませんね……

**Comment by ygkn** [comment]
> https://www.leo-webdesign.com/pc/
> 
> これとか、参考にできるかな？？
> もしあれだったらソースコード渡します！！

この手法がパララックスさせる要素ですが、パララックスさせる要素の親要素がそれぞれ`100vh*100vw`じゃないと使えないので使えませんね……。

**Comment by mizucoffee** [comment]
> @lra21711214 @mizucoffee ちなみにMacでパララックスの画像(`.parallax > .background`)に`will-change: transform;`を追加するとどうなります？

だめす

**Comment by lra21711214** [comment]
一年程度更新がないのでこのイシューをクローズしても大丈夫ですか？、、

**Comment by AkihiroTokai** [comment]
@lra21711214 @lit-kansai-members/admins  v2案件かなというところなのですがどうしましょう？

**Comment by ygkn** [comment]
とりあえずスクロール時にゆっくり動かす処理が重くてぐわんぐわんしてしまうよりは固定したほうがいいだろうということで PR  投げます！

PRでそれがOKかどうか話しましょう！
