### ISSUE TITLE
【New Song】雀ノ欠伸

### ISSUE THREAD

**Issue by AkihiroTokai** [lit-kansai-members/music#167]
When:Summer-2019 (信州3Days ）
Author:Saucy Dog
Lyric:http://j-lyric.net/artist/a05fdb9/l04c4cf.html
YouTube:https://www.youtube.com/watch?v=IJRdeZA05OE

**Comment by ygkn** [comment]
Saucy Dog :clap:

**Comment by mizucoffee** [comment]
全日程開始されたので開放OKです

**Comment by AkihiroTokai** [comment]
@mizucoffee 公開に向けた作業を開始しました！

**Comment by AkihiroTokai** [comment]
Refer to #171

**Comment by AkihiroTokai** [comment]
Refer to #171
