### ISSUE TITLE
Googleフォームが逝去

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/music#174]

**Comment by AkihiroTokai** [comment]
9月中は余裕ないのであれですが日本の消費税(標準税率)が10%になるころにはREAD MEの文言をうぴーdateします。

**Comment by AkihiroTokai** [comment]
~誰かやってくれてもeのよ。~

**Comment by ygkn** [comment]
R.I.P.

**Comment by AkihiroTokai** [comment]
👄

**Comment by AkihiroTokai** [comment]
これどこに誘導しましょうか。

**Comment by mizucoffee** [comment]
誰か直して...（せつじつ）

**Comment by AkihiroTokai** [comment]
さすがに404なのはアレですが新たに誘導する先をなんとかしたいですね。

**Comment by mizphses** [comment]
どうせPRかIssue打ってくれるので削除でいいんじゃないですか？

**Comment by AkihiroTokai** [comment]
@mizphses GitHubの操作がわからなくても一番手軽にできるかなというのはあるんですが関係各所に誘導する内容に変更してみます。

**Comment by AkihiroTokai** [comment]
do you have some information  のところにlinkが残ってるのでReopenします。(当該箇所はFacebookに変更予定)
