### ISSUE TITLE
Worng lyrics link: 'シュガーソングとビターステップ'

### ISSUE THREAD

**Issue by ygkn** [lit-kansai-members/music#186]
'16 Summer Camp のシュガーソングとビターステップの歌詞のリンクが CAN'T STOP THEE FEELING! の歌詞のリンクになっていた

**Comment by AkihiroTokai** [comment]
@ygkn invalidとwontfixについてはそれぞれ次のような認識で運用しています。こちらのcaseについては現時点でどちらも該当しないと思われるのでRemoveしておきますね。
invalid→間違えた　特定の事象を再現できず対応不要など
wontfix→開発の都合であえて修正しないなど

**Comment by ygkn** [comment]
なるほど〜

**Comment by AkihiroTokai** [comment]
ご参考までに。https://help.github.com/en/github/managing-your-work-on-github/about-labels

**Comment by AkihiroTokai** [comment]
@ygkn worngってなんですか（）

**Comment by ygkn** [comment]
さぁ

**Comment by AkihiroTokai** [comment]
:thinking:
