### ISSUE TITLE
Keep distance

### ISSUE THREAD

**Issue by AkihiroTokai** [lit-kansai-members/music#201]
@ygkn @mizucoffee @aptus-jp @RenMatsushita どこか離してみますか？w
https://twitter.com/lifeistechinc/status/1246742318842929152?s=21

**Comment by 7io63** [comment]
@AkihiroTokai
メッセージ部分にTabスペース入れたらいいんじゃないですか（）

>

**Comment by AkihiroTokai** [comment]
@7io63 どのメッセージですか？

**Comment by AkihiroTokai** [comment]
> Thanks for visit!
do you have some infomation?
Tell me withWeb Form
or
see this inGitHub
This project is an unoffcial.

@7io63 ここですかね。Textなので可読性を著しく損ねないことと表示崩れじゃなくてネタとわかる程度にはやることの両立がなかなか難しいところではあります。(#KeepDistanceとか付記しておいたらよさそう…？)

**Comment by 7io63** [comment]
ローディングアニメーション（勝手に水分取らないでetc）です
説明不足でした

**Comment by AkihiroTokai** [comment]
~TabSpaceとかbrとかやろうとしたら@ygknによって琵琶湖に沈められそう…~
🐥 🐥 🐥 🐥 🐥 🐥 🐥 🐥 🐥 🐥
#とびすけ10個分

**Comment by 7io63** [comment]
src/js/lit-words.js を #keepdistance #とびすけ10個分たしたり、tabは冗句にしても字間をcssであけるとかはどう?

**Comment by AkihiroTokai** [comment]
lit-wordsは新しいものも追加したいと思っていたところですしそこでいいと思います！他の人からも意見もらってみますね。

**Comment by AkihiroTokai** [comment]
>探さない、待つの。

@7io63 確認ですが例えばこれを
>探　さ　な　い　、　待　つ　の　。　#KeepDistance #とびすけ10個分

こうするということでしょうか。

**Comment by AkihiroTokai** [comment]
lit-wordsは短時間しか表示されないので他にわかりやすいところだと
そのあとに表示されるここでしょうか。
[ロゴ] [ロゴタイプ] [MUSICのtext]

**Comment by 7io63** [comment]
うーん、イメージとしては
・探　さ　な　い　、　待　つ　の　。
・🐥 🐥 🐥 🐥 🐥 🐥 🐥 🐥 🐥 🐥#KeepDistance #とびすけ10個分
・勝　手　に　水　分　と　ら　な　い　で

みたいな感じでスペースは通常版のやつに入れて、Keep Distanceとびすけは新規追加でいいかなー、と思ってます。

**Comment by AkihiroTokai** [comment]
@7io63 表示時間短いので短文のほうが分かりやすいとは思いますが、スペースだけでネタとして伝わるかどうかですね。そこが問題なさそうであれば可読性優先で:+1:

**Comment by AkihiroTokai** [comment]
Keep Distanceとびすけは期間限定じゃなく継続かな...？

**Comment by AkihiroTokai** [comment]
空白文字乱用するつもりなんて最初からないですがあらためて検討します。
https://gist.github.com/mala/08fdbc680d84bb1b2305688282f26cea

**Comment by mizucoffee** [comment]
http://www.htmq.com/style/letter-spacing.shtml

**Comment by AkihiroTokai** [comment]
最初から空白文字を使うつもりはないですが一応参考までに（）
https://gist.github.com/mala/08fdbc680d84bb1b2305688282f26cea

**Comment by AkihiroTokai** [comment]
最初から空白文字を使うつもりはないですが一応参考までに
https://gist.github.com/mala/08fdbc680d84bb1b2305688282f26cea

**Comment by ygkn** [comment]
もうブーム過ぎてる気がする

**Comment by AkihiroTokai** [comment]
@ygkn lit-wordsの内容追加に合わせて反映する想定です。

**Comment by AkihiroTokai** [comment]
@ygkn lit-wordsのContents追加に合わせて反映する想定です。
