### ISSUE TITLE
【New Song】スタートライン

### ISSUE THREAD

**Issue by AkihiroTokai** [lit-kansai-members/music#209]
When：Life is Hack! (Hello, World!!・Online#1)
Title：スタートライン
Author : ベリーグッドマン
YouTube：https://www.youtube.com/watch?v=MKKgw3X49Bc
Lyrics(J-Lyrics.net): http://j-lyric.net/artist/a058dc1/l04bf0b.html
Description：TBS アニメ　新幹線変形ロボ シンカリオン　ED
🎤 [DAM] [6211-82](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=6211-82) [JOYSOUND] [439760](https://www.joysound.com/web/search/song/755614)
Special Thanks：@souta0104  @risako070310 @sugijotaro ゆう　さっきー

**Comment by souta0104** [comment]
iizo!

**Comment by sugijotaro** [comment]
😍
