### ISSUE TITLE
【SpecialCase】'15Spring Music

### ISSUE THREAD

**Issue by ToukaiAkihiro** [lit-kansai-members/music#23]
@KawakawaRitsuki 特例で3人のおじさんを追加しませんか？

**Comment by KawakawaRitsuki** [comment]
どうしましょうか...

**Comment by KawakawaRitsuki** [comment]
全国区じゃないのがどうしても難点ですね。。。

**Comment by ToukaiAkihiro** [comment]
(KyotoCamp)と付記する方法もあると思いますが、本人の意見も聞きたいです

**Comment by KawakawaRitsuki** [comment]
本人ｗｗｗ
@OldBigBuddha
いかが致しましょう

**Comment by ToukaiAkihiro** [comment]
3人のおじさんを広めたのは@KinchanMikitoだと思いますw

**Comment by KawakawaRitsuki** [comment]
すべての元凶はそちらでしたかw

**Comment by ToukaiAkihiro** [comment]
本人からコメントを頂いていました。みなさんはどうでしたか？ 
> あったなそんな歌ww
> どれだけの人が覚えているか、それによるかな？www

**Comment by KawakawaRitsuki** [comment]
あくまでも個人的な意見ではありますが、あくまでLiT-Musicと銘打っているので全国区で流れていた曲に絞るべき、とは思っています。
とはいえ実際たくさん流れていたのも事実ではありますが。。。

MIYUKKIで流れていた曲は該当させないほうがいいとは思います。
とても増えてしまうので。

**Comment by ygkn** [comment]
僕はその場にいなかったのですがそう思います。

**Comment by KawakawaRitsuki** [comment]
かなり放置されてますがとりあえずCloseさせていただきます。
何かあればRe-Openお願いします。
