### ISSUE TITLE
【New Song】あの夢をなぞって

### ISSUE THREAD

**Issue by AkihiroTokai** [lit-kansai-members/music#234]
# Events :  2020-Summer

## Music Info

- Title : あの夢をなぞって

- Artist : YOASOBI 

- YouTube URL: https://www.youtube.com/watch?v=sAuEeM_6zpk

- Lyric : http://j-lyric.net/artist/a061652/l050f8b.html

- DAM: [5267-36](https://www.clubdam.com/karaokesearch/songleaf.html?requestNo=5267-36)

- JOYSOUND: [446885](https://www.joysound.com/web/search/song/822624)

# PIC
- GitHub ID: @AkihiroTokai (かんとく)

**Comment by AkihiroTokai** [comment]
@mizphses氏がせっかく作ってくれたのに活用しきれてなくて申し訳ないですがtempleteはあくまでも参考様式ということでお願いします。

**Comment by mizucoffee** [comment]
マージしてもらってもいいですかね...

**Comment by mizucoffee** [comment]
アップデートしていただけると...。

**Comment by AkihiroTokai** [comment]
@mizucoffee 定期Updateは他の人にやってもらえるといいかなと考えていましたがそれでいつまでも反映されないのもアレなのでやります（）
