### ISSUE TITLE
1Day消す

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/music#245]
全国じゃないもんね

**Comment by AkihiroTokai** [comment]
全国判定が難しいところですがそれを除外するとなると定例以外で微妙なの多くないですか。

**Comment by AkihiroTokai** [comment]
@mizucoffee 2020年6月8日21時39分に直接2人でおこなったmessengerでのやり取り（隠し条件）をご確認ください。

**Comment by mizucoffee** [comment]
@AkihiroTokai 隠し条件に関しては該当しないものではないかと

**Comment by AkihiroTokai** [comment]
mizucoffee 該当しないものではないということは掲載条件に該当しているということですよね？

**Comment by mizucoffee** [comment]
日本語難しい💢
「該当しないもの」「ではないかと」「思います」

**Comment by AkihiroTokai** [comment]
「全国じゃない」が意味するところが必ずしも明らかではないですが超特急ラインは他に掲載しているContentsと重複しておらず、参加者が限定されている（School参加者向けGWeventなど）ことや開催地域が限定されている（卒業サプライズやEnglish×IT Campなど）ものも掲載されていることから現時点では萩１dayを除外対象とする必要はなく、必要があれば条件を再検討しすでに掲載されているものに対しても個別に判断していくべきではないかと思います。

**Comment by mizucoffee** [comment]
@AkihiroTokai 15春の曲で重複してますね

**Comment by AkihiroTokai** [comment]
このDBで重複していることは確認しましたが、2015春のContentsとしての適否についてこちらで再確認してみますね。いわゆる体験会的な意味での1dayは他にないのでそういう意味では特記しなくていいような気もします。

**Comment by AkihiroTokai** [comment]
@lit-kansai-members/admins  @mizucoffee 2015春のContentsに超特急ラインが使用されていない可能性が高く、萩1day固有のものであると判断しました。固有（クリキャンのハピネスなど一部重複している場合も固有とみなす。）の曲が存在し、Life is Tech ! に関連したeventであるということから現時点では掲載対象であり（例外扱いしてもいいですが）、1day系を除外するなら別途条件を設ける必要があるのではないかと考えるのですがいかがでしょうか。

**Comment by E235-235** [comment]
2015春に参加したものですが、配布DVDでも超特急ラインは使用されています。

**Comment by E235-235** [comment]
誤ってCloseしてしまいました。大変申し訳ありません。

**Comment by E235-235** [comment]
2015春に参加した者ですが、Contents内で超特急ラインは頻繁に使用されています。
また参加者へのDVDにも収録されているため、それ以前の1Dayなどで使用されていない限りは萩1Day固有のものには該当しないと考えられます。
誤りがあれば申し訳ないです。

**Comment by AkihiroTokai** [comment]
@mizucoffee 基本的に1dayだとまとめ映像はあまりないですがありました？

**Comment by AkihiroTokai** [comment]
曲としての固有性がないのであれば海陽町を夏の一環とみなしているのと同じように春の一環ということにしてもいいですね。

**Comment by mizucoffee** [comment]
これあるって言うと採用されるやつですか？？？？？？？？？

**Comment by AkihiroTokai** [comment]
@mizucoffee それは総合的な判断になりますが、@lit-kansai-members/admins のみなさんなどのご意見も伺いつつ進めていきたいです。まとめ映像があったとしても海陽町は夏扱いですしね。 @E235-235から詳細を個人的に確認しているところですが、固有の曲がなく全体的に春の一環ならまとめていいんじゃないですかね。Tシャツはたしか定例Campのものでは？

**Comment by AkihiroTokai** [comment]
まとめ映像の有無に関して裏を取るかどうかという点でしたらCampの特殊性などを鑑みそれはそのまま採用します。

**Comment by mizucoffee** [comment]
Tシャツは15春キャンプのもの、まとめ映像に関しては件の曲です

**Comment by AkihiroTokai** [comment]
@E235-235 SpringCamp2015のOPmovieに超特急ラインが利用されていることの確認が取れました。ご協力ありがとうございます！
@lit-kansai-members/admins 総合的に判断してSpringCamp2015とまとめても問題なさそうですがいかがでしょうか。
