### ISSUE TITLE
Bug: YouTubeのサムネが出ない

### ISSUE THREAD

**Issue by mizphses** [lit-kansai-members/music#270]
## 起こっている状況
ＹｏｕＴｕｂｅのサムネが死んでる

## 環境
Windows10 20H2
Chromium Edge, Firefox, Lunascape Gecko各最新版で確認

**Comment by AkihiroTokai** [comment]
iPadOS 13.4.1 Safariでも確認しました。

**Comment by mizphses** [comment]
直した
