### ISSUE TITLE
【New Song】群青(YOASOBI)

### ISSUE THREAD

**Issue by AkihiroTokai** [lit-kansai-members/music#284]
## 流れていた曲

- 曲名: 群青

- Artist: YOASOBI

- YouTube URL: https://www.youtube.com/watch?v=Y4nEEZwckuU

- 歌詞サイトの URL: https://j-lyric.net/artist/a061652/l051a48.html

- DAM: 5285-69

- JOYSOUND: 486218

# 情報提供者

- GitHub ID: @AkihiroTokai 
- ニックネーム: かんとく

**Comment by AkihiroTokai** [comment]
@mizphses のあむさんにこちらの曲についてお伝えください

**Comment by mizphses** [comment]
今回のテーマ情報についてデータございませんでしょうか？
