### ISSUE TITLE
ティーンエイジサンセット

### ISSUE THREAD

**Issue by ayame-r** [lit-kansai-members/music#317]
## 流れていた曲

- 曲名: ティーンエイジサンセット(曲名)

- Artist: Hump Back（アーティスト名）

- YouTube URL: https://youtu.be/8fMem5-ONEg

- 歌詞サイトの URL: https://www.lyrical-nonsense.com/lyrics/hump-back/teenage-sunset/

- DAM: 5238-32

- JOYSOUND: 999236

# 情報提供者

- GitHub ID: @ayame-r（空白可）

- Twitter ID: @（空白可）

- ニックネーム: あやめ

**Comment by AkihiroTokai** [comment]
@ayame-r issueありがとうございます！4月4日が今回の最終日程なのでそれ以降にmergeしますね。

**Comment by AkihiroTokai** [comment]
@sugijotaro  J-Lyric.netにないので↑でOKです！
