### ISSUE TITLE
ココロノナカ

### ISSUE THREAD

**Issue by ayame-r** [lit-kansai-members/music#318]
## 流れていた曲

- 曲名: ココロノナカ(曲名)

- Artist: RADWIMPS（アーティスト名）

- YouTube URL: https://youtu.be/c604tpzZKCw

- 歌詞サイトの URL: https://j-lyric.net/artist/a04ac97/l051b90.html

- DAM: 7096-74

- JOYSOUND: 485392

# 情報提供者

- GitHub ID: @ayame-r（空白可）

- Twitter ID: @（空白可）

- ニックネーム: あやめ

**Comment by AkihiroTokai** [comment]
👍
