### ISSUE TITLE
【Uncertain information】Opening BGM

### ISSUE THREAD

**Issue by ToukaiAkihiro** [lit-kansai-members/music#36]
Openingで Can't Stop The Feeling がいつも使用されている可能性が高いと思いますが、いかがでしょうか？
https://youtu.be/ru0K8uYEZWw

**Comment by ygkn** [comment]
というと？

**Comment by ToukaiAkihiro** [comment]
具体的には受付からStartまでと体験会ですね。

**Comment by ToukaiAkihiro** [comment]
すでに16'Summerに追加されていたのでCloseします。

**Comment by KawakawaRitsuki** [comment]
16'Summerから外して下に書いてもいいですね

**Comment by ygkn** [comment]
春で流れていなかった気もしますが…
