### ISSUE TITLE
背景画像

### ISSUE THREAD

**Issue by ygkn** [lit-kansai-members/music#37]

**Comment by ygkn** [comment]
@KawakawaRitsuki すみませんもう一回送って下さい

**Comment by KawakawaRitsuki** [comment]
何のだっけ？

**Comment by KawakawaRitsuki** [comment]
伊豆？
https://life-is-tech.com/entry/izu201505/

**Comment by KawakawaRitsuki** [comment]
よしもと
https://life-is-tech.com/yoshimoto-techday/

**Comment by KawakawaRitsuki** [comment]
ミク1D
https://life-is-tech.com/miku_oneday/

**Comment by KawakawaRitsuki** [comment]
14英語
https://life-is-tech.com/englishitcamp/

**Comment by KawakawaRitsuki** [comment]
スクエニ
https://life-is-tech.com/square-enix-camp/
