### ISSUE TITLE
注意点体操歌詞 '15 Summer Camp

### ISSUE THREAD

**Issue by ygkn** [lit-kansai-members/music#38]
@KawakawaRitsuki @ToukaiAkihiro @OldBigBuddha 
どなたか情報提供おねがいします。

**Comment by ToukaiAkihiro** [comment]
@KawakawaRitsuki @OldBigBuddha 
暫定版ですが確認お願いします！最終確認後Commitする予定です。
> 
> さあみんな　注意点体操の時間だよ！
> 今日も元気に　いってみよう！
> 
> 注意点　注意点　注意点体操
> 
> 両手を前に　足を曲げる　開発
> 注意点体操
> 
> 休憩しないで開発してると疲れる　注意点体操
> のどがかわく　そのまま我慢　倒れる　注意点体操
> 勝手に消えると　運営スタッフ　焦るよ　注意点体操
> 深夜になっても　パソコンしてると　鬼来る
> 開発あそび　本気でやると楽しい　
> ランランランラン　ルンルンルンルン　楽しい　注意点体操
> 午前はねむい　お昼はあつい　食後もねむい　深夜はねない　注意点　注意点　注意点体操
> お肌のゴールデンタイムは夜10時から午前2時までだよ　ちゃんと寝ろよ

**Comment by ygkn** [comment]
とりあえずプルリクして、それからレビューしてもいいですよ～

**Comment by ygkn** [comment]
プルリクがないなら僕がpushしましょうか？

**Comment by ygkn** [comment]
@KawakawaRitsuki @OldBigBuddha
レビューお願いできます？

**Comment by KawakawaRitsuki** [comment]
:+1:

**Comment by ToukaiAkihiro** [comment]
#50

**Comment by ToukaiAkihiro** [comment]
#50 で対応しました。
