### ISSUE TITLE
Keep service URL

### ISSUE THREAD

**Issue by AkihiroTokai** [lit-kansai-members/music#439]
似たような名前のorganizationができましたが、URLとか維持したいのでこっちこのままでいいですか？

**Comment by AkihiroTokai** [comment]
@lit-kansai-members/admins

**Comment by mizucoffee** [comment]
当該organizationを存じ上げていないのでコメントしかねますが、息の長いorgですし他orgに影響されて名前を変更する必要はないかと思います。

**Comment by bearpoohkanayan** [comment]
こっちのorgはこのままでいいと思います！
メンバーの世代交代のたびに起こる現象だと思いますし後発に影響されて先発が何か変える必要はないかと、、

**Comment by AkihiroTokai** [comment]
@mizucoffee 
当該organizationこちらです。単純に似たようなものがいくつかあるとややこしいのではという懸念ですね。https://github.com/LiT-Kansai-Members-Org

**Comment by ren-suke** [comment]
似たような事をやりたいのであれば引き継ぎも兼ねてこのorgに入ってもらうのもありかなと思います

**Comment by inoren-ten** [comment]
突然申し訳ありません、[いのれん](https://x.com/inoren_lit)です🙇

この度関西メンバー数人でプロジェクトを始めることになり、新しくorgを作成することにしました。
ただ、世代は違えど、関西メンバーでの立ち上げというこちらと同じきっかけであるため、どうしても似たorgになってしまいます……

私が今回プロジェクトを立ち上げたのは、`関西のメンバー達が様々なプロジェクトを通して全員一丸となって成長すること`を目的としています。なので、こちらのorgを引き継がせていただくのは少し違うのかなと感じています。

勿論、先に立ち上げられたこのorgをリスペクトしていますので、こちらのみなさまに納得いただけないようなら、何かしらの形で対応したいと考えています。

GitHubのURLが紛らわしいということでしたら、昨晩対応し、こちらのGitHubのURLは[https://github.lit-kansai-members.com/](https://github.lit-kansai-members.com)で管理するようにいたしました。（[リポジトリ](https://github.lit-kansai-members.com/github-router)）

何卒、よろしくお願いいたします。

**Comment by AkihiroTokai** [comment]
@inoren-ten ご確認ご対応いただきありがとうございます。[かんとく](https://www.facebook.com/profile.php?id=100007979586197)です🙇
こちらのorganizationですが、lit-kansaiをリスペクトして始まり、Server・domainなどの管理運用で属人化しにくくするといった理由などでGitHub pagesを利用していたという経緯があります。
本件問題提起として、後先がどうということではなく、あくまでわかりやすさを目的としたものですので、すでにURL変更いただいたとのことですが、よりやりやすいしやすいかたちがあれば相談しましょう。
またorgのREADMEでお互いに紹介するといったことは可能でしょうか。
すてきなprojectが生まれることやmusicDBへのご参加期待しています。

**Comment by AkihiroTokai** [comment]
@inoren-ten @lit-kansai-members/admins 
draftですがorgのREADMEを設定してみました。この書き方だと新orgのほうで音楽関係やりにくいかもしれませんが😅そのときはまた必要に応じて見直しましょう！先ほど公開したdraftに対するご意見もお待ちしています。

**Comment by AkihiroTokai** [comment]
@inoren-ten 「2024年以前の」という表現だと2024年を含みどちらも該当しますし、移行したとも解釈できるので、「2023年以前からある」でいかがでしょうか。

**Comment by inoren-ten** [comment]
@AkihiroTokai 
確認ありがとうございます！
ただいま、対応いたしました！またご意見あればお願いします🙇

**Comment by AkihiroTokai** [comment]
@inoren-ten 
Smoothな対応ありがとうございます！
lit-kansaiに準拠した表記ゆれはあるのですが、このorganization名は「Life is Tech! Kansai Members」でお願いします🙇

**Comment by inoren-ten** [comment]
@AkihiroTokai
再び対応しました！
またご意見あればお願いします🙇🙇

**Comment by AkihiroTokai** [comment]
LGTM👍本件closeしてよければreactionください🙇
