### ISSUE TITLE
'16 Xmas Camp

### ISSUE THREAD

**Issue by ygkn** [lit-kansai-members/music#51]
B日程（~12/30）が終了してからmasterブランチにマージします。

- [x] 壁紙
- [ ] テーマソング
- [x] 注意点の歌詞

**Comment by ygkn** [comment]
それまでは[add/2016-xmas](https://github.com/lit-kansai-members/music/tree/add/2016-xmas)ブランチで開発します。

**Comment by ToukaiAkihiro** [comment]
👍

**Comment by KawakawaRitsuki** [comment]
個人的にはネタバレにならないという意図で待っているのであれば、既に全参加者に情報が回ってるはずなのでマージしても良いかと思います。

**Comment by ygkn** [comment]
閉じてなかったー()
