### ISSUE TITLE
Mac環境での描画崩れ

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#56]
## Description
Mac環境に於いてロゴ部に描画崩れが発生する。

## Image
PC版は全ての画像に於いて同じサイズで画像を取得している。
SafariとChromeは同じ描画、Firefoxのみ別の崩れ方をしている。
### Safari
<img width="568" alt="safari" src="https://cloud.githubusercontent.com/assets/9247699/22325168/45acb320-e3f0-11e6-8474-03997a4f5814.png">

### Chrome
<img width="568" alt="chrome" src="https://cloud.githubusercontent.com/assets/9247699/22325247/8b34ee26-e3f0-11e6-846c-9ba7a7dcce05.png">

### Firefox
<img width="568" alt="ff" src="https://cloud.githubusercontent.com/assets/9247699/22325190/4e6076b4-e3f0-11e6-9ca5-cd755554047a.png">

### Chrome 幅をモバイル相当
<img width="341" alt="screen shot 2017-01-26 at 5 55 32 pm" src="https://cloud.githubusercontent.com/assets/9247699/22325324/d9ff427c-e3f0-11e6-890b-338d02907aac.png">

### Firefox 幅をモバイル相当
<img width="341" alt="screen shot 2017-01-26 at 5 56 24 pm" src="https://cloud.githubusercontent.com/assets/9247699/22325354/ee48c776-e3f0-11e6-8924-760937df6e73.png">

**Comment by ygkn** [comment]
具体的にはMUSICの位置どうしたらいいかな？

**Comment by KawakawaRitsuki** [comment]
## 本家ロゴ
![lifeistech-logo](https://cloud.githubusercontent.com/assets/9247699/22422473/dd771636-e72f-11e6-8ae7-d1eb4d86c804.png)

## Chromeの表示
<img width="568" alt="chrome" src="https://cloud.githubusercontent.com/assets/9247699/22422479/e8cc038e-e72f-11e6-8a50-a3a27f3f47a3.png">

## Firefoxの表示
<img width="568" alt="firefox" src="https://cloud.githubusercontent.com/assets/9247699/22422487/f14008e4-e72f-11e6-939e-08127edf4a30.png">

MUSICの位置はChromeが理想、Life is Tech!の文字はどっちもずれてるけどFFが近い。

**Comment by ygkn** [comment]
なるほどぉ～
ありがとうございました！
至急直させていただきます！

**Comment by ygkn** [comment]
あ原因わかった

**Comment by ygkn** [comment]
@kawakawaritsuki
直りました？

**Comment by KawakawaRitsuki** [comment]
MUSICズレてる（ちょろめ）
FFの表示に近くなってるし改善はされてるねー

**Comment by ygkn** [comment]
修正しましたー。
どうです？

ちなみにコンソールから

```js
document.body.classList.toggle("loaded")
```

で何回もアニメーション実行できますです。

**Comment by KawakawaRitsuki** [comment]
Very good🎉🎉🎉
修正されていることを確認しました！
スマートフォンサイズも大丈夫そうですね！

Closeして頂いて結構です :D

**Comment by ygkn** [comment]
よかったですー。
実はJSで実装してたアニメーションを全てCSSにしてパフォーマンスの改善もされてたんですよ :smile:

**Comment by KawakawaRitsuki** [comment]
...って思ったけどFirefoxががが

**Comment by KawakawaRitsuki** [comment]
キャッシュ消して確認し直してきます

**Comment by ygkn** [comment]
今 push したやつのビルドが走ってるのでもうちょいお待ちください

**Comment by KawakawaRitsuki** [comment]
現状のズレは今朝のChromeと同じですね。
ビルド待ちですね

**Comment by ygkn** [comment]
ご確認ください！

**Comment by KawakawaRitsuki** [comment]
<img width="628" alt="screen shot 2017-02-20 at 6 53 33 pm" src="https://cloud.githubusercontent.com/assets/9247699/23120018/fd6f810c-f79d-11e6-86f4-1d7a8000b060.png">

Firefoxです...
ずれてますね...MUSIC...

もう神経質にならないのも手段かとは思いますが（）

**Comment by KawakawaRitsuki** [comment]
今更でアレですが画像化などはどうでしょうか...
イマイチか...

**Comment by ygkn** [comment]
svgにしました！
どうでしょう

**Comment by ygkn** [comment]
MUSIC部分のフォントは[Lato](https://fonts.google.com/specimen/Lato)のBoldです。

**Comment by KawakawaRitsuki** [comment]
Congratulations🎉
Firefox,Chrome共に確認しました！

欲を言えば、画像同士の謎の隙間がもうちょい詰めれればとは思いますが、本Issueのメインテーマであるズレは解決したのでクローズさせていただきます。

気が向いたらお願いします;D

**Comment by ygkn** [comment]
なるほど！こういうことでしょうか？

**Comment by ygkn** [comment]
HTML上のスペースが表示上現れておたので`display:flex`で回避しました

**Comment by KawakawaRitsuki** [comment]
Very good!XD

Thx!
