### ISSUE TITLE
キャンプ毎のタイトルの背景に色をつけて欲しい

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#60]
Life is Tech!の白い壁紙の時、境界線が消えるので、ごくごく薄い灰色とかでも良いので色をつけていただきたいです。

**Comment by ygkn** [comment]
なるほどわかりました！

**Comment by ygkn** [comment]
タイトルの背景ではなく、画像がないところの背景に色をつけてみましたがどうでしょう？

**Comment by KawakawaRitsuki** [comment]
いいですねー！これで良いと思います！
ありがとうございます！
