### ISSUE TITLE
[BOT（サンプル）] 曲の提案 'Happily'

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#62]
## 曲の提案 ### タイトル：Happily ### 歌手：One Direction ### URL：https://www.youtube.com/watch?v=s28PuyRqLrs ###キャンプ名：'15 春キャンプ

**Comment by KawakawaRitsuki** [comment]
うーんカオス

**Comment by ygkn** [comment]
Bot?

**Comment by KawakawaRitsuki** [comment]
Bot

**Comment by KawakawaRitsuki** [comment]
闇から抜け出せた気がするからClose

**Comment by ygkn** [comment]
Google Formからやってんの？

**Comment by KawakawaRitsuki** [comment]
気づいてなかったやーん（）
Google Form + GASですね。
