### ISSUE TITLE
add CampTheme

### ISSUE THREAD

**Issue by ToukaiAkihiro** [lit-kansai-members/music#68]
各Campのテーマソングとして採用されている曲はそのCampのテーマ(e.g. 2015Spring -> SurpriseEverything)とも関連していると思うので、Camp見出し下部にそのCampのテーマを記載してもいいと思います。

**Comment by KawakawaRitsuki** [comment]
分かる範囲で良いので一覧などをいただけると幸いです。
私も分かる範囲では調べますが限界があると思います（）

**Comment by KawakawaRitsuki** [comment]
伊豆：一年に一度だけ、地獄のような ３日間

**Comment by KawakawaRitsuki** [comment]
2017春：閃け！春！Spark
2016冬：一年に一度だけ、特別な数日間。
2016夏：世界なんてひと夏で変わる。

**Comment by KawakawaRitsuki** [comment]
そろそろ本気でまとめていきますかね

**Comment by KawakawaRitsuki** [comment]
14春:出会い、別れ、はじまり
14夏:夏のすべてが詰まってる
14冬:一年に一度だけ、魔法のような4日間
15春:すべてがサプライズの春キャンプへ
15夏:世界で一番、ココロ踊る「夏」を。
15冬:5日間だけの魔法の世界へ、ようこそ
16春:まだ見ぬ世界に全力でワクワクしよう。
16夏:世界なんて、ひと夏で変わる。
16冬:一年に一度だけ、特別な数日間。
17春:閃け！春！Spark

15年よりサブタイトルが入ります。

15春:Surprise Everything
15夏:A SUMMER THAT ROCKS YOUR HEART
15冬:Make with Magic
16春:Next World
16夏:LIVE AN ADVENTUROUS
16冬:
17春:Spark! Spring!

**Comment by KawakawaRitsuki** [comment]
更新は僕がしますね

**Comment by ToukaiAkihiro** [comment]
@KawakawaRitsuki Thanks!

**Comment by KawakawaRitsuki** [comment]
>すべてがサプライズの春キャンプへ -Surprise Everything-

ですかねぇ

**Comment by KawakawaRitsuki** [comment]
また、これ以前の情報や間違いを随時募集中です！

**Comment by KawakawaRitsuki** [comment]
尚16冬のテーマを知っている方がいらっしゃいましたら教えていただければ幸いです。
DVDの表紙にある英文です。

**Comment by KawakawaRitsuki** [comment]
とりあえず今回の目標は達成したのでクローズします。
テーマ募集については別途Formを用意します。 #72
