### ISSUE TITLE
サイトのレンダリングの挙動が怪しい

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#69]
## 確認環境
```
Vivaldi	1.8.770.50 (Stable channel) (64-bit)
Revision	a7960a843c0fff6e0faaaa8edc19df6a3bef2456
OS	Mac OS X 
JavaScript	V8 5.7.492.65
```
及びMac上のSafari、Firefoxでも確認しました。
その他、別のMacでも確認しました。
また、自分の記憶ではMac以外でも起きていたと思うのですが未確認です。

## 概要
Mac上にて、スクロールするとガク付きます。

**Comment by ygkn** [comment]
```
OS: Ubuntu 16.04.2 LTS x86_64 
品番: PC-GN276GSDA 
カーネル: 4.8.0-41-generic
CPU: Intel i7-7500U (4) @ 3.5GHz 
GPU: Intel Integrated Graphics 
メモリ: 8GB
```
で検証してみたところ、Google Chrome (57.0.2987.133)、Vivaldi (1.8.770.54、V8 5.7.492.72) では確認されませんでしたが、Firefox (52.0.2)では多少のガクつきが確認されました。

**Comment by ygkn** [comment]
Windows上の同バージョンのChrome上でもガクつきは確認されませんでした。

**Comment by KawakawaRitsuki** [comment]
'''
Google Chrome	57.0.2987.133 (Official Build) （64 ビット）
変更履歴	ec33cd0c06881d919ac0de419d829ad914e0be8f-refs/branch-heads/2987@{#887}
OS	Windows 10 Creative
JavaScript	V8 5.7.492.71
Flash	25.0.0.148 C:\Users\Mizucofee\AppData\Local\Google\Chrome\User Data\PepperFlash\25.0.0.148\pepflashplayer.dll
ユーザー エージェント	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
'''

Scroll Downボタンで多少のガクつきを確認しました。
単純にレンダリング速度の問題で高速移動だともたつく可能性もありえます。

**Comment by ygkn** [comment]
RAF内の動作が重いのかな？

**Comment by KawakawaRitsuki** [comment]
これ画面が広いと起こりやすいっぽいです。。。

**Comment by ygkn** [comment]
RAF内で`getBoundingClientRect()`してるのが原因らしい。
参考: http://blog.anatoo.jp/entry/2015/10/14/174403

**Comment by KawakawaRitsuki** [comment]
おおおお？！

**Comment by ygkn** [comment]
しかし他にパララックスどころか固定する方法ないよねっていう

**Comment by ygkn** [comment]
改善はしましたー。。。。

**Comment by KawakawaRitsuki** [comment]
初期から比較するとかなり改善自体はしてるんですよね。。。ただ単純に遅い（ラグい）っていう。。。
凄くクローズしたいけど解決はしてないのでとりあえずlow priorityにして置いときますかね。。。

**Comment by KawakawaRitsuki** [comment]
```
Google Chrome | 61.0.3163.100 (Official Build) (64-bit)
Revision | 57c9d07b416b5a2ea23d28247300e4af36329bdc-refs/branch-heads/3163@{#1250}
OS | Mac OS X
JavaScript | V8 6.1.534.41
Flash | 27.0.0.183 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
```

このバージョンで治ってる事を確認しました．
Chrome，JS共にメジャーアップデート来てるんでその辺ですかね...
