### ISSUE TITLE
過去キャンプテーマ募集

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#72]
過去のキャンプのテーマを募集するフォームを作る。

**Comment by ygkn** [comment]
:+1:

**Comment by KawakawaRitsuki** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSefqsiMlk6Kr9G-Xxcu5CpKfntP_f7KjZX6Q8Gd8VrGK6uVdw/viewform?c=0&w=1
追加した。Scriptしゅーせーします。

**Comment by KawakawaRitsuki** [comment]
Scriptがそもそも意味をなしてなくて辛い

**Comment by KawakawaRitsuki** [comment]
修正しました。
