### ISSUE TITLE
[Example] テーマの提案 "2015年スプリングキャンプ"

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#74]
### 提案者

ごっちゃん

### キャンプ名：

2015年スプリングキャンプ

### メインテーマ：

すべてがサプライズの春キャンプへ

### サブテーマ：

Surprise Everything

**Comment by KawakawaRitsuki** [comment]
こんな感じでいいですかね

**Comment by ygkn** [comment]
いいと思うー

**Comment by KawakawaRitsuki** [comment]
じゃあこれで行きますね～
