### ISSUE TITLE
Webページに提案Formへのリンクを張る

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#75]
URL: https://docs.google.com/forms/d/e/1FAIpQLSefqsiMlk6Kr9G-Xxcu5CpKfntP_f7KjZX6Q8Gd8VrGK6uVdw/viewform?c=0&w=1

一番下のスペースか左上とかにボタンを付けるか。。。

**Comment by ygkn** [comment]
一番下に配置して横のナビゲーションで「！」としておきましょうかね

#78

**Comment by KawakawaRitsuki** [comment]
これ解決してますね
