### ISSUE TITLE
fork meいる？

### ISSUE THREAD

**Issue by mizucoffee** [lit-kansai-members/music#78]
```
do you have some infomation?
fork me on GitHub
```

の必要性に疑問を感じる。。。
曲投稿はフォームで良いしそもそもこのプロジェクトforkするメリットとは。。。うごごごご

**Comment by ygkn** [comment]
定型文的な感じでなんとなくつけてたけどいらんな()

**Comment by ygkn** [comment]
やっぱり情報提供だけじゃなくてページそのものの場合 fork me on... ってなるのでは

**Comment by KawakawaRitsuki** [comment]
いやそうなんですけど、あくまでProjectとしてのfork me onであってサイトがメインの場合のfork me onは違和感を覚えます。。。

**Comment by KawakawaRitsuki** [comment]
Fork me onやめてこのサイトのプロジェクトページっていう感じのリンクに変更しよう

**Comment by ygkn** [comment]
See this in GitHub?

**Comment by AkihiroTokai** [comment]
↑に変更しておきます。
