### ISSUE TITLE
add 注意点 2017Spring

### ISSUE THREAD

**Issue by ToukaiAkihiro** [lit-kansai-members/music#82]
ブルゾンちえみに関連した注意点ネタ3本の歌詞追加しませんか？

**Comment by KawakawaRitsuki** [comment]
いいですね。歌詞把握してらっしゃいますか？

**Comment by ToukaiAkihiro** [comment]
(改行を読点で、字幕に表記されていない部分を括弧で表しています。)
田口くんありがとう(#注 社員名？がもう1人入る) 木村くんありがとう
みんな拾ってくれてありがとう
ああ女に生まれてよかった
どうも
安全第一がモットー
リスク管理の徹底ぶり
注意点ヒューマンです
キャンプに来てくれた、Life is Tech ! メンバーのみんな
さっきの注意点、自分には関係ないって思ってない？
じゃあ 質問です
みんなが勝手にいなくなったら、私達運営は (一体)どうすると 思いますか？
探さない 待つの
待ってるわ
(だって) カバンはここにあるんだから
注意
ヒューマン

**Comment by KawakawaRitsuki** [comment]
他種類は把握されてない感じですかね？

**Comment by ygkn** [comment]
その場合ブルゾンちえみの動画も追加する感じですか？

**Comment by KawakawaRitsuki** [comment]
そうなりますね

**Comment by ToukaiAkihiro** [comment]
@KawakawaRitsuki 他の注意点も順次テキストにします！

**Comment by ygkn** [comment]
@ToukaiAkihiro :+1:  よろしくお願いします！

**Comment by KawakawaRitsuki** [comment]
@ToukaiAkihiro 中の人に聞けないですかね

**Comment by ToukaiAkihiro** [comment]
@KawakawaRitsuki 検討します...

**Comment by japanetf** [comment]
注意点ヒューマン(社長が来た会場は流されてます:早稲田5days・東大など)

どうも、安全第一がモットー、リスク管理 の徹底ぶり、
注意点ヒューマンです
キャンプにも慣れて来たみんな、
これであなたもライフイズテック通？
じゃあ質問です。
ライフイズテック代表のみっちー、
今年で何歳か わかりますか？
35~6(歳)

35~6(歳)

**Comment by KawakawaRitsuki** [comment]
@japanetf 
情報提供ありがとうございます！
とても助かります！

**Comment by ToukaiAkihiro** [comment]
@japanetf 
社長が来てない会場（SFC,名古屋,HALなど）でも確認しています！
ご協力ありがとうございます！

**Comment by japanetf** [comment]
あと社員さんの名前は
https://lifeistech.co.jp/what/team/
を見て、音から見ると
築比地 健太さんかなと。

**Comment by japanetf** [comment]
それと、これ以外の１つってエンディングのですか？

**Comment by ToukaiAkihiro** [comment]
社員の名前は⏰のプロ👏経由で注意点Humanに確認してもらいましたが、松井 晋平 さんだそうです。

**Comment by japanetf** [comment]
でしたらここに書きますね。
しんぺーさんでしたか。。。

**Comment by ToukaiAkihiro** [comment]
"Life is Tech !が最後にSurpriseを仕掛けないことなんてあると思いますか？"ですねｗ

**Comment by japanetf** [comment]
あれです

**Comment by ToukaiAkihiro** [comment]
「Life is Tech! は気が利くので✋」:smile:

**Comment by japanetf** [comment]
はあくされてますか？

**Comment by japanetf** [comment]
されてましたねー

失礼しました

**Comment by ToukaiAkihiro** [comment]
撮影andデータがあるので大丈夫です:ok_hand:

**Comment by ygkn** [comment]
やりますね
