### ISSUE TITLE
各項目のレンダリング

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#84]
曲名、歌手名のレンダリングおかしくないですか？
![53b7a2ebf1ef7a90c35937107a7190af](https://cloud.githubusercontent.com/assets/9247699/25769865/cab58cdc-325f-11e7-8700-413506162da2.png)

凄く上に寄ってる気がします

**Comment by ygkn** [comment]
了解しましたー。
修正しますー！
