### ISSUE TITLE
各項目へのリンク

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#85]
各項目へのリンクが欲しいです。。。が、ちょっと良く考えて作らないとまずそうですね。。。

**Comment by ygkn** [comment]
各項目へのリンクというと？

**Comment by KawakawaRitsuki** [comment]
urlの最後に何かしらのタグとかIDを付けてその項目に飛べるようにしたい。。。
/music#1
で１つ目。みたいな...
ただ途中に追加したときにズレるから考えねば

**Comment by ygkn** [comment]
もう実装してたり（）
キャンプ名/年名をクリック

**Comment by KawakawaRitsuki** [comment]
あ、説明不足申し訳ない。
URLで指定したいんですよねー

**Comment by ygkn** [comment]
http://lit-kansai-members.github.io/music/#a--16-Summer-Camp
こういうことではない？

**Comment by KawakawaRitsuki** [comment]
んんｗｗｗｗ知らなかったｗ
それですｗ

出来れば右メニュー押した時にも同じ機能を付けていただければ直感的かもです。。。

**Comment by ygkn** [comment]
おっけです！
なおしときますねー
