### ISSUE TITLE
日本語化

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#86]
英語にする理由があまりないので日本語にしていく方針で行きたいと思います。

**Comment by KawakawaRitsuki** [comment]
Thanks for visit!はそのままに

このWebページは非公式のものであり有志が制作したものです。
もし何かあればLife is Tech!社ではなくこちらのページ(Github)までお願いします。

また、知っている情報等々ございましたらこちらのフォームから投稿してください！

だっ

**Comment by ToukaiAkihiro** [comment]
ja/enでいいじゃなイカ

**Comment by KawakawaRitsuki** [comment]
enの必要性

**Comment by ygkn** [comment]
制作陣みんな日本人で外国人のカケラもいないのに日本語化のIssue建てられるの笑う

**Comment by KawakawaRitsuki** [comment]
日本人って英語に憧れるんです
