### ISSUE TITLE
【Change】Coca-Cola Campのbackground

### ISSUE THREAD

**Issue by ToukaiAkihiro** [lit-kansai-members/music#87]
背景画像ですが変更する場合どちらがいいと思いますか？

**Comment by ToukaiAkihiro** [comment]
![project_main_cocacola_20151227](https://cloud.githubusercontent.com/assets/11627142/26730969/8ee61390-47ed-11e7-9d26-71e723e0c97c.jpg)

**Comment by ToukaiAkihiro** [comment]
↑の画像中央にこの画像を合成したもの
![project_entry_main_coca](https://cloud.githubusercontent.com/assets/11627142/26730998/9d9e29c2-47ed-11e7-94f6-571130bffcfe.png)

**Comment by ygkn** [comment]
背景なので合成しなくてもいい感はありますね

**Comment by ToukaiAkihiro** [comment]
@ygkn  一応公式のバナーは合成したものなんですよね…

**Comment by KawakawaRitsuki** [comment]
まあ @ygkn の言うとおり背景に文字があって読むかって考えると。。。とは思いますね。

**Comment by ygkn** [comment]
背景は `/res/img/backgrounds/` にぶち込んで `index.yml` の各曲の `background` プロパティいじってもらえば設定できます

**Comment by ToukaiAkihiro** [comment]
日付が変わったらうぴーしますｗ

**Comment by ygkn** [comment]
:smile:

**Comment by KawakawaRitsuki** [comment]
これやりますね

**Comment by KawakawaRitsuki** [comment]
というかどう考えても背景と同化するのでそのまま採用します（ゴリ押し

**Comment by ygkn** [comment]
@KawakawaRitsuki Good Job! :+1:
