### ISSUE TITLE
【Can't Play】さよならメモリーズ

### ISSUE THREAD

**Issue by AkihiroTokai** [lit-kansai-members/music#88]
さよならメモリーズがBlockされているので代替Contents調査します！

**Comment by ygkn** [comment]
:+1:

**Comment by KawakawaRitsuki** [comment]
どうですか！

**Comment by ToukaiAkihiro** [comment]
進捗ダメです

**Comment by KawakawaRitsuki** [comment]
Oh...

**Comment by ToukaiAkihiro** [comment]
これはどうですか？
https://www.youtube.com/watch?v=kZn3bIO4fAQ

**Comment by japanetf** [comment]
多分それカバーです。
niconicoでいいんだったらhttp://www.nicovideo.jp/watch/sm9286217
dailymotionはhttp://www.dailymotion.com/video/x2pfk6v
officialはないですね。

**Comment by KawakawaRitsuki** [comment]
@japanetf 情報ありがとうございます！
検討してみますね...！

**Comment by ToukaiAkihiro** [comment]
@KawakawaRitsuki  Remind

**Comment by ToukaiAkihiro** [comment]
https://www.youtube.com/watch?v=ZP9mJdpENMg

**Comment by ToukaiAkihiro** [comment]
https://www.youtube.com/watch?v=ZP9mJdpENMg

**Comment by mizucoffee** [comment]
supercellめちゃくちゃ消えますね

**Comment by AkihiroTokai** [comment]
TravisCI の件を解消しないと進められないですが、再生できない状態を確認したのでReOpenしておきます。

**Comment by AkihiroTokai** [comment]
＠7io63 YouTube以外にも対応する計画はあるのでそちらでの解決が図れるといいですね。

**Comment by AkihiroTokai** [comment]
@mizucoffee @ygkn これCoverしか見つからなかったのでチェンジユアワールドと同等の対応にしますか？それともCoverにしておきますか？

**Comment by AkihiroTokai** [comment]
Remind @mizucoffee @lit-kansai-members/admins

**Comment by AkihiroTokai** [comment]
@lit-kansai-members/admins @mizucoffee @mizphses チェンジユアワールドと同等の対応にしておきます。なにかあればReopenしてください。
