### ISSUE TITLE
[Form] 曲の提案 "見たこともない景色"

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#89]
### 提案者

りゅうせい/くあてろ　(@ryusei_lit)

### タイトル：

Life 那須 Tech!

### 歌手：

菅田 将暉

### URL：

https://youtu.be/1aeRjU19VtE

### キャンプ名：

Life 那須 Tech!

**Comment by ToukaiAkihiro** [comment]
ともきさんからも5月6日にmessenger経由で情報提供していただいていました()
