### ISSUE TITLE
下にコントロールバー欲しくない...?

### ISSUE THREAD

**Issue by KawakawaRitsuki** [lit-kansai-members/music#94]
nicobox的なアレ

**Comment by ygkn** [comment]
どんなん

**Comment by KawakawaRitsuki** [comment]
画面下部に固定的な

![がぞー](http://blog.nicovideo.jp/niconews/Androidnicobox_info2.png)
再生中の動画の名前/再生停止

PCだったら右下なのかなあ...これは面倒くさそうだしまあ...

**Comment by ygkn** [comment]
実装しとった
