### ISSUE TITLE
【add】(Summer)CampPoem

### ISSUE THREAD

**Issue by ToukaiAkihiro** [lit-kansai-members/music#99]
2017 Summer 
Theme「夏が君を動かす。君が世界動かす。Move」

Summer moves your heart. You inspire the World .

夏は不思議な力を持っている。

何かに夢中になりたくなる。
誰かとはしゃぎたくなる。
秘密を語り合いたくなる。
新しい自分を見たくなる。

夏が君を突き動かす。
そこからすべてが始まる。

君が動くことで、世界は動き始める。
この夏のテーマは「Move」

世界を動かす、感動させる特別な夏へようこそ！

**Comment by ygkn** [comment]
キャンプテーマをクリックしたらモーダルウィンドウで開くようにします？

**Comment by ygkn** [comment]
themeプロパティに複数行の文字を入れたたらモーダル開くリンクにするとか
